const API_ENDPOINT = 'http://localhost:3001';
const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
const ADD_POST = 'ADD_POST';
const EDIT_POST = 'EDIT_POST';
const DELETE_POST = 'DELETE_POST';
const RECEIVE_POSTS = 'RECEIVE_POSTS';
const UPDATE_POST_VOTE_COUNT = 'UPDATE_POST_VOTE_COUNT';
const REQUEST_POSTS = 'REQUEST_POSTS';
const ADD_COMMENT = 'ADD_COMMENT';
const EDIT_COMMENT = 'EDIT_COMMENT';
const DELETE_COMMENT = 'DELETE_COMMENT';

export {
    API_ENDPOINT,
    REQUEST_CATEGORIES,
    RECEIVE_CATEGORIES,
    ADD_POST,
    EDIT_POST,
    DELETE_POST,
    RECEIVE_POSTS,
    UPDATE_POST_VOTE_COUNT,
    REQUEST_POSTS,
    ADD_COMMENT,
    EDIT_COMMENT,
    DELETE_COMMENT,
};
