const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
const REQUEST_POSTS = 'REQUEST_POSTS';
const RECEIVE_POSTS = 'RECEIVE_POSTS';
const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
const ADD_POST = 'ADD_POST';
const UPDATE_POST = 'UPDATE_POST';
const DELETE_POST = 'DELETE_POST';
const UPDATE_POST_VOTE_COUNT = 'UPDATE_POST_VOTE_COUNT';
const ADD_COMMENT = 'ADD_COMMENT';
const EDIT_COMMENT = 'EDIT_COMMENT';
const DELETE_COMMENT = 'DELETE_COMMENT';

export {
    REQUEST_CATEGORIES,
    RECEIVE_CATEGORIES,
    REQUEST_POSTS,
    RECEIVE_POSTS,
    ADD_POST,
    UPDATE_POST,
    DELETE_POST,
    UPDATE_POST_VOTE_COUNT,
    REQUEST_COMMENTS,
    RECEIVE_COMMENTS,
    ADD_COMMENT,
    EDIT_COMMENT,
    DELETE_COMMENT,
};
